sudo: required
services:
  - docker

before_install:
  - docker build -t joshuabpare/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joshuabpare/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-east-1-389311491362"
  bucket-path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
